### ISSUE TITLE
Edits for prepare.MD - bold means inserted, italics means rearranged, cross out means removed

### ISSUE THREAD

**Issue by MIZwally** [nimh-dsst/abcd-fasttrack2bids#29]
Part 1:

1. Go to https://nda.nih.gov/ and **log into your account** (click `LOGIN` in the top right)
2. Click on the `Get Data` > `Get Data` tab **in the menu** up top
3. Go to `Data Dictionary` > `Data Structures` on the left
4. Search for `abcd_fastqc01`
5. Click the checkbox to the left of `ABCD Fasttrack QC Instrument`
6. Click `ADD TO WORKSPACE` in the bottom right
7. Click on the _little filter icon with the number 1 on it in the top right_
8. Click `SUBMIT TO FILTER CART` in the bottom right of this new pane
9. Wait for `Filter Cart (0)` **in the top right** to change to `Filter Cart (1)`, **then click on it**
~10. Click on the `Filter Cart (1)` icon in the top right~
11. Click on `Create Data Package/Add Data to Study`
12. Click `Create Data Package`
    * Name the package something informative like `abcdqcYYYYMMDD` (note: special characters are not allowed)
    * Select Only `Include documentation`
    * Click `Create Data Package`
~Navigate to your NDA dashboard and from your NDA dashboard, click Data Packages.~ **Click on `My Account` > `Data Packages` on the top right to find your new package.** You should see the data package ~that you just created~ with a status of `Creating Package`. It takes roughly 10 minutes for the NDA to create this package. When it's ready to download the status will change to `Ready to Download`

**Comment by MIZwally** [comment]
Part 2:

**The instructions for this package are similar to those for the fastqc package.**

1. ~Go to https://nda.nih.gov/ and click LOGIN on the top right~ **Follow steps 1 and 2 from above**
2. ~Click on the Get Data > Get Data tab up top~
3. Click on `Data from Labs` on the left
4. Search for `abcd study`
5. Click on the checkbox to the left of ABCD Study, **making sure that the collection id is 2573** ~which you'll see on the right is collection 2573~
6. ~Click ADD TO WORKSPACE in the bottom right~ **Follow steps 6-12 from above. For step 9, it may take a couple of hours for the filter cart to update**
7. ~Click on the top right on the little filter icon with the number 1 on it~
8. ~Click SUBMIT TO FILTER CART in the bottom right of this new pane~
9. ~Wait for the Filter Cart (0) to change to Filter Cart (1), this may take a couple hours…~
10. ~Click on the Filter Cart (1) icon in the top right~
11. ~Click on Create Data Package/Add Data to Study~
12. ~Click Create Data Package~
    * ~Name the package something informative like abcdYYYYMMDD (note: special characters are not allowed)~
    * ~Check the box that says Include Associated Data Files~
    * ~Click Create Data Package~

You can check the status of this package by navigating back to the `Data Packages` tab within your profile. You should see your newly created package at the top of the table with a status of `Creating Package`. _This data package is 300+TB in size and may take up to a day to be created._ Wait until the status changes to `Ready to Download` before proceeding. Make note of this Package ID as it will be needed to convert.

**Comment by ericearl** [comment]
Resolved with e09e1e5.
